[package]
name = "rust_modbus_client" # the name of the package
version = "0.1.0" # the current version, obeying semver
edition = "2021" # the edition of Rust to use

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-modbus = "0.10.0"